url: wss://bpt-lab.org/bp2017w1-controller

chainScripts:
  start: ./private_chain_scripts/start_{}.sh
  stop: ./private_chain_scripts/stopChain.sh
  scaleMiner: ./private_chain_scripts/scale_{}.sh
  scaleLazy: ./private_chain_scripts/lazyNodes_{}.sh

ethereumPort: 20000
multichainPort: 200000
xainPort: 20000


chains:
- chainName: ethereum
  parameter:
  - selector: numberOfHosts
    name: Number of hosts
  - selector: numberOfMiners
    name: Number of miners
  - selector: startChain
  - selector: stopChain
  - selector: scenario

- chainName: xain
  parameter:
  - selector: numberOfHosts
    name: Number of hosts
  - selector: numberOfMiners
    name: Number of miners
  - selector: startChain
  - selector: stopChain
  - selector: scenario

- chainName: multichain
  parameter:
  - selector: numberOfHosts
    name: Number of hosts
  - selector: numberOfMiners
    name: Number of miners
  - selector: startChain
  - selector: stopChain
  - selector: scenario
