url: ws://localhost:4040

chainScripts:
  start: ./private_chain_scripts/start_{}.sh
  switch: ./private_chain_scripts/switchChainToFrom.sh
  scale: ./private_chain_scripts/scale_{}.sh


target: target
chains:
- chainName: ethereum
  parameter:
  - selector: numberOfHosts
    name: Number of hosts
  - selector: numberOfMiners
    name: Number of miners

- chainName: xain
  parameter:
  - selector: numberOfHosts
    name: Number of hosts
  - selector: numberOfMiners
    name: Number of miners

- chainName: multichain
  parameter:
  - selector: numberOfHosts
    name: Number of hosts
  - selector: numberOfMiners
    name: Number of miners
